export class Card{
  cards = [
    { professione: 'WEB DEVELOPER',  title: '60k', country: 'naples', description: 'Sei un appassionato di sviluppo web alla ricerca di un ambiente stimolante e dinamico? Unisciti al nostro team di esperti per creare esperienze digitali coinvolgenti e innovative. Collabora con designer e sviluppatori per trasformare concetti creativi in soluzioni web di alta qualità. Se sei pronto a mettere in mostra le tue abilità e a contribuire a progetti entusiasmanti, inviaci il tuo curriculum oggi stesso!' },
    { professione: 'WEB DEVELOPER',  title: '60k', country: 'naples', description: 'Sei un appassionato di sviluppo web alla ricerca di un ambiente stimolante e dinamico? Unisciti al nostro team di esperti per creare esperienze digitali coinvolgenti e innovative. Collabora con designer e sviluppatori per trasformare concetti creativi in soluzioni web di alta qualità. Se sei pronto a mettere in mostra le tue abilità e a contribuire a progetti entusiasmanti, inviaci il tuo curriculum oggi stesso!' },
    { professione: 'WEB DEVELOPER',  title: '60k', country: 'naples', description: 'Sei un appassionato di sviluppo web alla ricerca di un ambiente stimolante e dinamico? Unisciti al nostro team di esperti per creare esperienze digitali coinvolgenti e innovative. Collabora con designer e sviluppatori per trasformare concetti creativi in soluzioni web di alta qualità. Se sei pronto a mettere in mostra le tue abilità e a contribuire a progetti entusiasmanti, inviaci il tuo curriculum oggi stesso!' },
    { professione: 'WEB DEVELOPER',  title: '60k', country: 'naples', description:  'Sei un appassionato di sviluppo web alla ricerca di un ambiente stimolante e dinamico? Unisciti al nostro team di esperti per creare esperienze digitali coinvolgenti e innovative. Collabora con designer e sviluppatori per trasformare concetti creativi in soluzioni web di alta qualità. Se sei pronto a mettere in mostra le tue abilità e a contribuire a progetti entusiasmanti, inviaci il tuo curriculum oggi stesso!' },
    { professione: 'WEB DEVELOPER',  title: '60k', country: 'naples', description: 'Sei un appassionato di sviluppo web alla ricerca di un ambiente stimolante e dinamico? Unisciti al nostro team di esperti per creare esperienze digitali coinvolgenti e innovative. Collabora con designer e sviluppatori per trasformare concetti creativi in soluzioni web di alta qualità. Se sei pronto a mettere in mostra le tue abilità e a contribuire a progetti entusiasmanti, inviaci il tuo curriculum oggi stesso!' },
    { professione: 'WEB DEVELOPER',  title: '60k', country: 'naples', description:  'Sei un appassionato di sviluppo web alla ricerca di un ambiente stimolante e dinamico? Unisciti al nostro team di esperti per creare esperienze digitali coinvolgenti e innovative. Collabora con designer e sviluppatori per trasformare concetti creativi in soluzioni web di alta qualità. Se sei pronto a mettere in mostra le tue abilità e a contribuire a progetti entusiasmanti, inviaci il tuo curriculum oggi stesso!' },
    { professione: 'WEB DEVELOPER',  title: '60k', country: 'naples', description: 'Sei un appassionato di sviluppo web alla ricerca di un ambiente stimolante e dinamico? Unisciti al nostro team di esperti per creare esperienze digitali coinvolgenti e innovative. Collabora con designer e sviluppatori per trasformare concetti creativi in soluzioni web di alta qualità. Se sei pronto a mettere in mostra le tue abilità e a contribuire a progetti entusiasmanti, inviaci il tuo curriculum oggi stesso!' },
    { professione: 'WEB DEVELOPER',  title: '60k', country: 'naples', description: 'Sei un appassionato di sviluppo web alla ricerca di un ambiente stimolante e dinamico? Unisciti al nostro team di esperti per creare esperienze digitali coinvolgenti e innovative. Collabora con designer e sviluppatori per trasformare concetti creativi in soluzioni web di alta qualità. Se sei pronto a mettere in mostra le tue abilità e a contribuire a progetti entusiasmanti, inviaci il tuo curriculum oggi stesso!' },
    { professione: 'WEB DEVELOPER',  title: '60k', country: 'naples', description: 'Sei un appassionato di sviluppo web alla ricerca di un ambiente stimolante e dinamico? Unisciti al nostro team di esperti per creare esperienze digitali coinvolgenti e innovative. Collabora con designer e sviluppatori per trasformare concetti creativi in soluzioni web di alta qualità. Se sei pronto a mettere in mostra le tue abilità e a contribuire a progetti entusiasmanti, inviaci il tuo curriculum oggi stesso!' },
    { professione: 'WEB DEVELOPER',  title: '60k', country: 'naples', description:  'Sei un appassionato di sviluppo web alla ricerca di un ambiente stimolante e dinamico? Unisciti al nostro team di esperti per creare esperienze digitali coinvolgenti e innovative. Collabora con designer e sviluppatori per trasformare concetti creativi in soluzioni web di alta qualità. Se sei pronto a mettere in mostra le tue abilità e a contribuire a progetti entusiasmanti, inviaci il tuo curriculum oggi stesso!' },
    { professione: 'WEB DEVELOPER',  title: '60k', country: 'naples', description: 'Sei un appassionato di sviluppo web alla ricerca di un ambiente stimolante e dinamico? Unisciti al nostro team di esperti per creare esperienze digitali coinvolgenti e innovative. Collabora con designer e sviluppatori per trasformare concetti creativi in soluzioni web di alta qualità. Se sei pronto a mettere in mostra le tue abilità e a contribuire a progetti entusiasmanti, inviaci il tuo curriculum oggi stesso!' },
    { professione: 'WEB DEVELOPER',  title: '60k', country: 'naples', description:  'Sei un appassionato di sviluppo web alla ricerca di un ambiente stimolante e dinamico? Unisciti al nostro team di esperti per creare esperienze digitali coinvolgenti e innovative. Collabora con designer e sviluppatori per trasformare concetti creativi in soluzioni web di alta qualità. Se sei pronto a mettere in mostra le tue abilità e a contribuire a progetti entusiasmanti, inviaci il tuo curriculum oggi stesso!' },
  ];

}
